### ISSUE TITLE
Possible Issue with miku !== 39 when converting Vraki

### ISSUE THREAD

**Issue by Skibinski** [Deovandski/vraki-windows#2]
Miku is currently being matched with "r-qk`ld" when converting when it supposed to be 39. Also "ku" is being appended between conversions.

**Comment by Deovandski** [comment]
Can be repeated when converting "MINISTRÁ-LOS" around with Simple Vraki.

**Comment by Deovandski** [comment]
Root of the issue was the non-standard pattern of Miku and 39 conversion which tripped the algorithms.

**Comment by Deovandski** [comment]
Fix will be live on 1.4
